var fname = "Abhi";
// fname = "Abhi";
var newname = fname.toLowerCase();
console.log(newname);
// let a : string[];
var b;
b = [1, 2, 3];
console.log(b);
// a = [];
// a.push("A");
// a.push('N');
// a.forEach( val => console.log(val));
// console.log(a);
